import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import JotaiDevTools from "@/utils/jotai-devtools";
import ReactQueryProvider from "@/providers/rq-provider";
import MainProviders from "@/providers/main-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isDevelopment = process.env.NODE_ENV !== "production";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <MainProviders>
            <JotaiDevTools shouldDisplay={isDevelopment}>
              <ReactQueryProvider shouldDisplay={isDevelopment}>
                {children}
              </ReactQueryProvider>
            </JotaiDevTools>
          </MainProviders>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
